# changing the shape of an array

In [1]:
import numpy as np # first import numpy

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr.shape

(10,)

In [5]:
arr.reshape((5,2),order = "C")

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

The shape of an array can be changed with various commands. Note that the following three commands all return a modified array, but do not change the original array:

In [6]:
arr.reshape((5,2),order = "F" )

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [7]:
arr.reshape(2,-1)
# If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
arr.resize((5,2)) # change array shape in memory
# np.resize(arr,(2,5))

In [9]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [10]:
arr.shape

(5, 2)

In [11]:
arr.T # return the array ,transposed

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [12]:
arr.T.shape

(2, 5)

In [13]:
arr.shape

(5, 2)

In [14]:
arr.ravel("F")

array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

In [15]:
arr.flatten("F") # Column major

array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

In [16]:
arr.shape

(5, 2)

In [17]:
arr.shape

(5, 2)

In [18]:
arr.flatten("F")

array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

In [19]:
arr.shape

(5, 2)

# C Versus Fortran Order

Numpy gives you control and flexibility over the layout of your data in memory.

C/row major order

Traverse higher dimensions first (e.g., axis 1 before advancing on axis 0).

Fortran/column major order

Traverse higher dimensions last (e.g., axis 0 before advancing on axis 1).

# concatening

In [20]:
arr1 = np.arange(6).reshape(3,2)

In [21]:
arr2 = np.arange(6).reshape(3,2)

In [22]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [23]:
arr2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [24]:
np.concatenate((arr1,arr2) , axis = 0 )

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [25]:
np.concatenate((arr1,arr2),axis = 1)

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

# stacking

In [26]:
np.vstack((arr1,arr2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [27]:
np.hstack((arr1,arr2))

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [28]:
np.dstack((arr1,arr2))

array([[[0, 0],
        [1, 1]],

       [[2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5]]])

In [29]:
d = np.array([2,3,4])
e = np.array([5,6,7])
np.column_stack((d,e))

array([[2, 5],
       [3, 6],
       [4, 7]])

# spliting

In [30]:
arr6 = np.random.randn(6, 2)

In [31]:
arr6

array([[-0.67430814,  1.29653989],
       [-0.77056976, -1.09790203],
       [-1.27341768,  2.07408066],
       [ 0.33797678,  1.0384364 ],
       [-0.93363732,  0.10577265],
       [ 1.72134205, -0.47511099]])

In [47]:
x ,y ,z = np.split(arr6,[3,5])# ider hum us ko bata hn k kitni rows utha k lani hn.

In [48]:
x

array([[-0.67430814,  1.29653989],
       [-0.77056976, -1.09790203],
       [-1.27341768,  2.07408066]])

In [49]:
y

array([[ 0.33797678,  1.0384364 ],
       [-0.93363732,  0.10577265]])

In [50]:
z

array([[ 1.72134205, -0.47511099]])

In [36]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [37]:
arr2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [38]:
np.c_[arr1,arr2]

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [39]:
np.r_[arr1,arr2]

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

# Repeating Elements: tile and repeat

In [40]:
a1 = np.arange(6)

In [41]:
a1

array([0, 1, 2, 3, 4, 5])

In [42]:
a1.repeat(4)

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5,
       5, 5])

In [43]:
a2 = np.random.rand(5,3)

In [44]:
a2

array([[0.51476623, 0.32988801, 0.17756584],
       [0.74748567, 0.48436309, 0.05459965],
       [0.30036759, 0.24885876, 0.97015678],
       [0.74502368, 0.57122169, 0.59508797],
       [0.75011459, 0.74697968, 0.27572998]])

In [45]:
a2.repeat(2,axis = 1)

array([[0.51476623, 0.51476623, 0.32988801, 0.32988801, 0.17756584,
        0.17756584],
       [0.74748567, 0.74748567, 0.48436309, 0.48436309, 0.05459965,
        0.05459965],
       [0.30036759, 0.30036759, 0.24885876, 0.24885876, 0.97015678,
        0.97015678],
       [0.74502368, 0.74502368, 0.57122169, 0.57122169, 0.59508797,
        0.59508797],
       [0.75011459, 0.75011459, 0.74697968, 0.74697968, 0.27572998,
        0.27572998]])

In [46]:
a3 = np.random.randn(5, 5)