# Array Creation

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3]) # right way
# b = np.array(1,2,3) # wrong way


In [3]:
a

array([1, 2, 3])

In [4]:
a.size

3

In [5]:
a.dtype

dtype('int32')

In [6]:
a.ndim

1

In [7]:
c = np.array([(1,2,3),(4,5,6)]) # array creation in 2_dim 

In [8]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr_1 = np.zeros(4) # array creation in 1_dim

In [10]:
arr_1

array([0., 0., 0., 0.])

In [11]:
arr_2 = np.zeros((3,4))# array creation in 2_dim
arr_2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
arr_3 = np.zeros((3,4,5)) # array creation in 3_dim
arr_3

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [13]:
arr_4 = np.zeros_like((2,4,6))

In [14]:
arr_4

array([0, 0, 0])

In [15]:
arr_5 = np.ones((3,5,6), dtype = np.int16) # dtype can also be specified

In [16]:
arr_5

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]], dtype=int16)

In [17]:
arr_6 = np.arange(2,20,2).reshape(3,3)
arr_6

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [18]:
arr_7 = np.empty((3,4))
arr_7

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
arr_8 = np.full((2,4) ,10) #Return a new array with shape of input filled with value

In [20]:
arr_8

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

# Basic Operation

In [21]:
A = np.arange(3,30,3).reshape(3,3)
A

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [22]:
B = np.arange(2,20,2).reshape(3,3)
B

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [23]:
C = A*B # elementwise 
D = A@B # matrix product
E = A.dot(B)# another way of product
print(C)
print(D)
print(E)

[[  6  24  54]
 [ 96 150 216]
 [294 384 486]]
[[180 216 252]
 [396 486 576]
 [612 756 900]]
[[180 216 252]
 [396 486 576]
 [612 756 900]]


Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [24]:
d = np.arange(15).reshape(5,3)
print(d)
print(d.sum())
print(d.max())
print(d.min())
print(d.sum(axis= 0))# sum of each column
print(d.sum(axis= 1))#  sum of each row

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
105
14
0
[30 35 40]
[ 3 12 21 30 39]


# Universal Function

In [25]:
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [26]:
np.exp(d)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06]])

In [27]:
np.sqrt(d)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739]])

In [28]:
np.square(d)

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196]], dtype=int32)

# Shape Manipulation

In [29]:
e = np.arange(12).reshape(4,-1)
e

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

What is difference between ravel and flatten?

ravel does not produce a copy of the underlying values if the values in the result
were contiguous in the original array. The flatten method behaves like ravel except
it always returns a copy of the data.


In [30]:
e.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
e.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# C Versus Fortran Order

C/row major order

Traverse higher dimensions first (e.g., axis 1 before advancing on axis 0).

Fortran/column major order

Traverse higher dimensions last (e.g., axis 0 before advancing on axis 1

# Concatening And Spliting 

In [32]:
arr3 = np.array([(1,2,3),(4,5,6)])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr4 = np.array([(7,8,9),(10,11,12)])
arr4

array([[ 7,  8,  9],
       [10, 11, 12]])

In [34]:
np.concatenate((arr3,arr4),axix = 0)

TypeError: 'axix' is an invalid keyword argument for concatenate()