# Basics

In [1]:
import numpy as np

In [2]:
#Write a NumPy program to get the numpy version and show numpy build configuration.
print(np.__version__)
print(np.show_config())

1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib'

In [3]:
#Write a NumPy program to  get help on the add function. 
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

# array_creation

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.

In [4]:
a = np.arange(15).reshape(3,5)
print(a)
print(a.shape) # for finding shape
print(a.dtype)# for finding type of element
print(a.ndim)# for finding dimension
print(a.size)# for finding size of element 
print(a.itemsize) # he size in bytes of each element of the array..32/8

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
int32
2
15
4


In [5]:
#b = np.array(1,2,3)  wrong method 
c = np.array([1,2,3]) # right method
print(c)

[1 2 3]


# 1_dimension

In [6]:
arr_1d = np.arange(15)
arr_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
list_1 = [1,3,5,7,8]
arr_1 = np.array(list_1)
print(arr_1)

[1 3 5 7 8]


# 2_dimensions

In [8]:
arr_2d = np.arange(20).reshape(4,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
arr_2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# 3_dimensions

In [10]:
arr_3d = np.arange(20).reshape(2,5,2 ,order = "C") # C order means row major .by default row he major hoti hain.

In [11]:
arr_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [12]:
arr = np.arange(30).reshape(3,2,5,order ="F") # F order means coloumn major.
arr

array([[[ 0,  6, 12, 18, 24],
        [ 3,  9, 15, 21, 27]],

       [[ 1,  7, 13, 19, 25],
        [ 4, 10, 16, 22, 28]],

       [[ 2,  8, 14, 20, 26],
        [ 5, 11, 17, 23, 29]]])

In [13]:
# One of the passed shape dimensions can be –1, in which case the value used for that
#dimension will be inferred from the data.
arr3 = np.arange(20).reshape(5,-1) # arr3 = np.arange(20).reshape(5,-2)
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

ravel does not produce a copy of the underlying values if the values in the result
were contiguous in the original array. The flatten method behaves like ravel except
it always returns a copy of the data:

In [14]:
arr3.ravel("C")

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
arr3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
arr3.flatten("F")

array([ 0,  4,  8, 12, 16,  1,  5,  9, 13, 17,  2,  6, 10, 14, 18,  3,  7,
       11, 15, 19])

In [17]:
# Generate  some random data 
d = np.random.rand(5,4)

In [18]:
d

array([[0.23774906, 0.6466166 , 0.23969892, 0.74596373],
       [0.58494369, 0.57138495, 0.98269333, 0.17535761],
       [0.59949525, 0.9534691 , 0.65400543, 0.75844161],
       [0.54271284, 0.53013397, 0.68707933, 0.80786405],
       [0.3955472 , 0.06289688, 0.78771988, 0.84797238]])

In [19]:
# apply some basis operation 
e = d + d

In [20]:
e

array([[0.47549812, 1.2932332 , 0.47939784, 1.49192746],
       [1.16988739, 1.14276989, 1.96538665, 0.35071522],
       [1.19899049, 1.9069382 , 1.30801085, 1.51688323],
       [1.08542567, 1.06026794, 1.37415867, 1.61572811],
       [0.7910944 , 0.12579377, 1.57543975, 1.69594476]])

In [21]:
d * 5

array([[1.18874531, 3.233083  , 1.19849461, 3.72981864],
       [2.92471846, 2.85692473, 4.91346664, 0.87678805],
       [2.99747623, 4.76734549, 3.27002713, 3.79220807],
       [2.71356418, 2.65066986, 3.43539666, 4.03932027],
       [1.97773599, 0.31448442, 3.93859938, 4.23986189]])

In [22]:
d.dtype

dtype('float64')

In [23]:
d.itemsize

8

In [24]:
d.size

20

In [25]:
 np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.zeros((3,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [28]:
np.empty((5,6))

array([[1.26933231e-311, 9.58487353e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 5.02034658e+175],
       [3.54404919e-061, 1.54607213e+185, 1.21093626e-071,
        1.24583117e-047, 5.01163187e+217, 5.49419094e-143],
       [9.80058441e+252, 1.30304358e-142, 2.14027814e+161,
        5.04621383e+180, 4.50618615e-144, 7.79952704e-143],
       [1.19002053e-047, 1.00086877e+165, 8.02973686e-042,
        6.87450836e+169, 1.41529403e+161, 9.16651763e-072],
       [3.88664254e+097, 3.38170851e-057, 4.26329512e+126,
        9.30350598e+199, 3.67152475e-062, 1.58268989e-319]])

# Basics Indexing and silicing

# 1_dimensions

In [29]:
arr4 = np.arange(15)
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
arr4[4] = 5

In [31]:
arr4

array([ 0,  1,  2,  3,  5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
arr4[2:4] = 0

In [33]:
arr4

array([ 0,  1,  0,  0,  5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
arr_slice = arr4[5:8]

In [35]:
arr_slice

array([5, 6, 7])

In [36]:
arr_slice[1] = 22

In [37]:
arr4

array([ 0,  1,  0,  0,  5,  5, 22,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
# if you want to copy of slice 
silice = arr4[5:8].copy()
silice

array([ 5, 22,  7])

In [39]:
silice[2] = 5

In [40]:
silice

array([ 5, 22,  5])

In [41]:
arr4

array([ 0,  1,  0,  0,  5,  5, 22,  7,  8,  9, 10, 11, 12, 13, 14])

# 2_dimensions

In [42]:
arr2 = np.arange(20).reshape(4,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [43]:
arr2[0][4]

4

In [44]:
arr2[0,4] # , is separator between rows and column.

4

In [45]:
arr2[0:2,1:3]

array([[1, 2],
       [6, 7]])

# 3_dimensions

In [46]:
arr3 = np.arange(40).reshape(4,5,2)
arr3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

# Boolean Indexing

In [47]:
names = np.array(["Joy","Bob",'raj',"kumar","Ali"])

In [48]:
data = np.random.rand(5,4)

In [49]:
data

array([[0.90844842, 0.38666261, 0.54736773, 0.69474914],
       [0.92360601, 0.01437831, 0.88475973, 0.69842568],
       [0.29823663, 0.64112807, 0.57103226, 0.97260709],
       [0.89214519, 0.49907805, 0.89960997, 0.02478654],
       [0.66558101, 0.15772999, 0.28709505, 0.31276375]])

In [50]:
data[names=="Bob"]

array([[0.92360601, 0.01437831, 0.88475973, 0.69842568]])

In [51]:
data[names == 'Bob', 2:]

array([[0.88475973, 0.69842568]])

In [52]:
data[1,2:]

array([0.88475973, 0.69842568])

# Fancy indexing

In [53]:
arr = np.empty((8,4))

In [54]:
for i in range(8):
    arr[i] = i
    

In [55]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [56]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

# Transposing Arrays and Swapping Axes

In [57]:
arr5 = np.arange(20).reshape(4,5)
arr5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [58]:
arr5.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

# Concatenating and Splitting Arrays

In [59]:
c1 = np.array([[1,2,3],[4,5,6]])
c2 = np.array([[7,8,9],[10,11,12]])

In [60]:
np.concatenate([c1,c2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
np.concatenate([c1,c2],axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [62]:
np.vstack([c1,c2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [63]:
np.hstack([c1,c2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [64]:
c3 = np.random.rand(6,3)

In [65]:
c3


array([[0.04416796, 0.03603575, 0.46057784],
       [0.4250325 , 0.03160095, 0.94483111],
       [0.38993621, 0.36768069, 0.58859066],
       [0.04785763, 0.05971155, 0.65744372],
       [0.51796642, 0.07852084, 0.48931465],
       [0.93756194, 0.04689997, 0.38153536]])

In [66]:
first, second, third = np.split(c3,[1,4])

In [67]:
first

array([[0.04416796, 0.03603575, 0.46057784]])

In [68]:
second

array([[0.4250325 , 0.03160095, 0.94483111],
       [0.38993621, 0.36768069, 0.58859066],
       [0.04785763, 0.05971155, 0.65744372]])

In [69]:
third

array([[0.51796642, 0.07852084, 0.48931465],
       [0.93756194, 0.04689997, 0.38153536]])

# Stacking helpers: r_ and c_

In [70]:
c6 = np.arange(6)
c7 = c6.reshape((3, 2))
c8 = np.random.randn(3, 2)
np.r_[c7, c8]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-1.62250536,  0.58476534],
       [ 0.75418805, -0.54416951],
       [ 0.05157622,  0.09955401]])

In [71]:
c7


array([[0, 1],
       [2, 3],
       [4, 5]])

In [72]:
c8

array([[-1.62250536,  0.58476534],
       [ 0.75418805, -0.54416951],
       [ 0.05157622,  0.09955401]])

In [73]:
np.c_[c7,c8]

array([[ 0.        ,  1.        , -1.62250536,  0.58476534],
       [ 2.        ,  3.        ,  0.75418805, -0.54416951],
       [ 4.        ,  5.        ,  0.05157622,  0.09955401]])

In [74]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [75]:
np.r_[1:6,-10:-5]

array([  1,   2,   3,   4,   5, -10,  -9,  -8,  -7,  -6])

# Repeating Elements: tile and repeat

In [76]:
new_arr = np.arange(4)
new_arr

array([0, 1, 2, 3])

In [77]:
new_arr.repeat(4)

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [78]:
np.repeat(new_arr,[2,4,5,3])

array([0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3])

In [79]:
new_arr.repeat([5,6,7,8])

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3])

In [80]:
new_arr1 = np.random.rand(2,2)

In [81]:
new_arr1

array([[0.21203465, 0.99573799],
       [0.5191854 , 0.18385759]])

In [102]:
new_arr1.repeat([2,3],axis = 0)

array([[0.21203465, 0.99573799],
       [0.21203465, 0.99573799],
       [0.5191854 , 0.18385759],
       [0.5191854 , 0.18385759],
       [0.5191854 , 0.18385759]])

In [83]:
new_arr1.repeat([3,2],axis = 1)

array([[0.21203465, 0.21203465, 0.21203465, 0.99573799, 0.99573799],
       [0.5191854 , 0.5191854 , 0.5191854 , 0.18385759, 0.18385759]])

In [84]:
new_arr2 = np.arange(20).reshape(2,2,5)

In [85]:
new_arr2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [99]:
np.tile(new_arr2,(2,3))

array([[[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
        [ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9,  5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14, 10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 15, 16, 17, 18, 19, 15, 16, 17, 18, 19],
        [10, 11, 12, 13, 14, 10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 15, 16, 17, 18, 19, 15, 16, 17, 18, 19]]])

In [101]:
np.tile(new_arr2,(3,2,2))

array([[[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
        [ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 15, 16, 17, 18, 19],
        [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
        [ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 15, 16, 17, 18, 19],
        [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
        [ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9,  5,  6,  7,  

# Fancy Indexing Equivalents: take and put

In [103]:
arr = np.arange(10)* 100

In [104]:
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])