# Indexing And Slicing

In [1]:
import numpy as np

# Basic Indexing

# 1_dimensions

In [2]:
arr_1 = np.arange(20)

In [3]:
arr_1 # index start from zero

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
arr_1[4]

4

In [5]:
arr_1[3:5]

array([3, 4])

In [6]:
arr_1[2:10:2] # here 2 is starting point and also include, 10 is ending point and also exclude 2 is step 

array([2, 4, 6, 8])

In [7]:
arr_1[3:5] = 23

In [8]:
arr_1

array([ 0,  1,  2, 23, 23,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 2 dimensions

In [10]:
arr_2 = arr_1[5:8]
arr_2

array([5, 6, 7])

In [11]:
arr_2d[2]

array([7, 8, 9])

In [12]:
arr_2d[2][2]

9

In [13]:
arr_2d[2,2] # axis 0 as the “rows” of the array and axis 1 as the “columns

9

In [14]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr_2d[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr_2d[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [18]:
arr_2d[:2, 1:]# here , is separator between rows and column

array([[2, 3],
       [5, 6]])

In [19]:
arr_2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [26]:
arr_2d[1:,1:2]

array([[5],
       [8]])

In [28]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr_2d[1,:2]

array([4, 5])

In [30]:
arr_2d[:2,2]

array([3, 6])

In [34]:
arr_2d[2,1]

8

# 3 dimensions

In [21]:
arr_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
arr_3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr_3d[0][1][2]

6

In [24]:
old_values =arr_3d[0].copy()

In [25]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

# Boolean Indexing

In [35]:
names = np.array(["joy","bob","raja","kami","sam","tom","jam"])

In [36]:
names

array(['joy', 'bob', 'raja', 'kami', 'sam', 'tom', 'jam'], dtype='<U4')

In [37]:
data = np.random.rand(7,4)
data

array([[0.55004763, 0.22516455, 0.31381877, 0.15202223],
       [0.09226505, 0.00589242, 0.23039913, 0.54499947],
       [0.67472283, 0.30993543, 0.28135379, 0.52612658],
       [0.90333178, 0.67726669, 0.74400174, 0.11736416],
       [0.8868283 , 0.99504159, 0.13354259, 0.22616099],
       [0.7879667 , 0.02715917, 0.02907925, 0.84876253],
       [0.68621301, 0.58631783, 0.41370955, 0.47671925]])

In [38]:
names == "bob"

array([False,  True, False, False, False, False, False])

In [39]:
data[names=="bob",:2]

array([[0.09226505, 0.00589242]])

In [40]:
data[1,:2]

array([0.09226505, 0.00589242])

In [41]:
data[names=="bob"]

array([[0.09226505, 0.00589242, 0.23039913, 0.54499947]])

In [42]:
data[names=="joy",:1] # data[0,:1]

array([[0.55004763]])

In [50]:
data[~(names == 'bob')]# 
#data[1]

array([[0.09226505, 0.00589242, 0.23039913, 0.54499947]])

In [49]:
data[1]

array([0.09226505, 0.00589242, 0.23039913, 0.54499947])

In [51]:
#boolean arithmetic operators like & (and) and | (or).