# Indexing And Slicing

In [1]:
import numpy as np

In [2]:
arr_1 = np.arange(20)

In [3]:
arr_1 # index start from zero

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
arr_1[4]

4

In [5]:
arr_1[3:5]

array([3, 4])

In [6]:
arr_1[2:10:2] # here 2 is starting point and also include, 10 is ending point and also exclude 2 is step 

array([2, 4, 6, 8])

In [7]:
arr_1[3:5] = 23

In [8]:
arr_1

array([ 0,  1,  2, 23, 23,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 2 dimensions

In [33]:
arr_2 = arr_1[5:8]
arr_2

array([5, 6, 7])

In [11]:
arr_2d[2]

array([7, 8, 9])

In [12]:
arr_2d[2][2]

9

In [13]:
arr_2d[2,2] # axis 0 as the “rows” of the array and axis 1 as the “columns

9

In [23]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr_2d[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr_2d[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [28]:
arr_2d[:2, 1:]# here , is separator between rows and column

array([[2, 3],
       [5, 6]])

In [29]:
arr_2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [32]:
arr_2d[1:,1:2]

array([[5],
       [8]])

# 3 dimensions

In [34]:
arr_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
arr_3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr_3d[0][1][2]

6