# introduction of numpy

NumPy, short for Numerical Python, is one of the most important foundational packages for numerical computing in Python.

# The NumPy ndarray: A Multidimensional Array Object 

In [2]:
import numpy as np

In [3]:
# Generate some random data
data = np.random.randn(2,4)
data

array([[-0.38382013,  0.47756091,  1.46797921, -1.21639202],
       [ 0.54207663,  0.88793471, -1.81690964,  0.05474057]])

In [5]:
 data1 = data *10

In [6]:
data1

array([[ -3.83820126,   4.77560914,  14.67979205, -12.16392019],
       [  5.42076632,   8.87934708, -18.16909644,   0.54740567]])

In [7]:
data1 + data

array([[ -4.22202139,   5.25317005,  16.14777126, -13.38031221],
       [  5.96284295,   9.76728179, -19.98600608,   0.60214623]])

In [8]:
# how to find shape of data
data1.shape

(2, 4)

In [9]:
#how to find type of data 
data1.dtype

dtype('float64')

# creating ndim array

In [11]:
list = [3,6,9,12,15]
array1 = np.array(list)
array1

array([ 3,  6,  9, 12, 15])

In [13]:
type(array1)

numpy.ndarray

In [15]:
list2 = [[1,2,3],[4,5,6]]
array2 = np.array(list2)
print(array2)
print(array2.dtype)

[[1 2 3]
 [4 5 6]]
int32


In [17]:
# how to find dimensions of array
array2.ndim

2

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((5,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
np.empty((2,5,6))

array([[[8.78106147e-312, 8.78099940e-312, 2.17388884e-321,
                     nan, 3.82368604e-297, 3.63370579e-292],
        [1.41431056e-309, 7.05896488e-278, 1.30316544e-258,
         2.40579058e-239, 4.44135843e-220, 8.19923932e-201],
        [1.51366943e-181, 1.14083506e-176, 9.91401238e-278,
         6.49724715e-273, 2.79054640e-263, 5.83290226e-302],
        [2.38469049e-244, 3.37496979e-239, 1.19333549e-152,
         2.88507523e-220, 1.23931385e-210, 1.20158320e-152],
        [3.19326582e-268, 7.93529696e-301, 1.19837475e-152,
         3.19444888e-268, 4.42022816e-297, 4.65414403e-273]],

       [[4.45864888e-220, 3.05132290e-268, 2.00010264e-263,
         1.31104133e-258, 8.59370549e-254, 5.63306202e-249],
        [6.45081009e-302, 5.08457180e-148, 2.75641217e-292,
         3.33222500e-143, 1.19365864e-152, 6.81391104e-225],
        [6.46903795e-302, 1.43117973e-133, 1.58740869e-234,
         3.54072498e-191, 1.52102399e-181, 2.32134730e-186],
        [9.97203872e-177, 2.93

In [10]:
 n1 = np.ones((5,7))
n1

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [11]:
n1.dtype

dtype('float64')

In [12]:
n1.astype("int16")
#You can explicitly convert or cast an array from one dtype to another using ndarray’s astype method


array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int16)

In [20]:
# for example you have data in string
n2 =np.array(["78",7,9,0,5],dtype = np.string_) 
print(n2)
print("Before changing type")
print(n2.dtype)
print("After changing type")
print(n2.astype(float))
print(n2.astype(int))

[b'78' b'7' b'9' b'0' b'5']
Before changing type
|S2
After changing type
[78.  7.  9.  0.  5.]
[78  7  9  0  5]


In [22]:
np.arange(20) # woek like range function

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])