# Universal Functions: Fast Element-Wise Array Function


In [1]:
import numpy as np

In [2]:
arr = np.arange(20)

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [5]:
arr_1 = np.arange(30).reshape(5,6)
arr_1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [6]:
arr_1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
arr_1.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [8]:
arr_1.ravel("C")#Traverse higher dimensions first (e.g., axis 1 before advancing on axis 0).rows major

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [9]:
arr_1.ravel("F")#Traverse higher dimensions last (e.g., axis 0 before advancing on axis 1).column major

array([ 0,  6, 12, 18, 24,  1,  7, 13, 19, 25,  2,  8, 14, 20, 26,  3,  9,
       15, 21, 27,  4, 10, 16, 22, 28,  5, 11, 17, 23, 29])

# Concatenating and Splitting Arrays

In [10]:
arr_2 = np.array([[1,2,3],[4,5,6]])
arr_2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr_3 = np.array([[7,8,9],[10,11,12]])
arr_3

array([[ 7,  8,  9],
       [10, 11, 12]])

In [13]:
arr_3.ndim

2

In [14]:
arr_3.dtype

dtype('int32')

In [15]:
arr_3.shape

(2, 3)

In [20]:
np.concatenate([arr_2,arr_3] ,axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
np.concatenate([arr_2,arr_3],axis = 1 )

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [23]:
np.vstack((arr_2, arr_3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
np.hstack((arr_2,arr_3))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [25]:
# split, on the other hand, slices apart an array into multiple arrays along an axis.

In [28]:
arr_5 = np.random.randn(6,2)

In [29]:
arr_5

array([[ 2.69134749,  0.33737941],
       [ 0.2587983 ,  0.17047499],
       [ 1.30600009, -1.30627593],
       [-0.32931681,  0.6474012 ],
       [ 1.16226089,  0.92360736],
       [ 0.83766189, -0.25404119]])

In [56]:
first,second,third = np.split(arr_5,[1,3])

In [57]:
first

array([[2.69134749, 0.33737941]])

In [58]:
second

array([[ 0.2587983 ,  0.17047499],
       [ 1.30600009, -1.30627593]])

In [59]:
third

array([[-0.32931681,  0.6474012 ],
       [ 1.16226089,  0.92360736],
       [ 0.83766189, -0.25404119]])