# Arithmetic with NumPy Arrays # 

In [1]:
import numpy as np

In [6]:
arr = np.array([[1,4,6],[5,7,8]])
arr

array([[1, 4, 6],
       [5, 7, 8]])

In [7]:
arr1 = arr * arr

In [8]:
print(arr1)

[[ 1 16 36]
 [25 49 64]]


In [9]:
arr2 = arr + arr
arr2

array([[ 2,  8, 12],
       [10, 14, 16]])

In [10]:
arr3 = arr - arr
arr3


array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
1 / arr

array([[1.        , 0.25      , 0.16666667],
       [0.2       , 0.14285714, 0.125     ]])

In [12]:
arr / 2

array([[0.5, 2. , 3. ],
       [2.5, 3.5, 4. ]])

In [13]:
arr ** 2

array([[ 1, 16, 36],
       [25, 49, 64]], dtype=int32)

In [16]:
 arr4 = arr2 > arr1
print(arr4)
print(arr4.ndim)
print(arr4.dtype)

[[ True False False]
 [False False False]]
2
bool


# reshaping array

In [18]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [23]:
a.reshape(4,2,order ="F") #  Fortran (column major) order


array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [24]:
a.reshape(2,4,order = "C")#  C (row major) 

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [25]:
a.ndim

1

In [27]:
a.reshape(4,2).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [34]:
b = np.arange(15)
b.reshape(5,-5)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [38]:
np.arange(60).reshape(6,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])